version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; poetry run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - .:/opt/app
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://user_test:pass_test@db/tech_test
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=pass_test
      - POSTGRES_DB=tech_test
      - PGDATA=/var/lib/postgresql/data

volumes:
  postgres_data:
